### ISSUE TITLE
Bug if Lat, Lng is in UTM zone M

### ISSUE THREAD

**Issue by bigw124** [rolfrander/geo#1]
I discovered a bug that was occurring in the Amazon Rainforest, when I tried converting from GPS coordinates -2.27418, -63.371 to UTM. I get a negative UTM northing. I realized that this was in UTM letter "m". I was able to get the conversion to work when I changed the code from this to:
       
     if (letter<'M')
	        northing = northing + 10000000;

 
      if (letter<='M')
	        northing = northing + 10000000;

I am not sure if this is correct since I do not have much understanding of the underlying Geographic procedure, but I was able to get the conversion to work in the Amazon by doing this. Let me know if this is correct, or if I am misunderstanding something.

**Comment by rolfrander** [comment]
I have not studied the details of the formula, but you are probably right, because the code for doing the opposite calculation checks for:

    if (letter>'M') {
        north = northing;
    } else {
        north = northing - 10000000;
    }

**Comment by zhughesjd** [comment]
Greetings rolfrandr,
First off, thanks for contributing your geo repo.
Pretty sure my comment here pertains to this bug.
In the current state of the code, executing the java line:

	System.out.println(new WGS84( new UTM(new WGS84(-2,-77))));

one would expect to see **"2.0S 77.0W"** printed out.
But as the code stands now **"86.9790179N 30.0875235W"** is printed out.
To fix this, change line 127 in UTM.java from **"if (letter<'M')"** to be **"if (letter<'N')"**
Then the above java statement prints out **"2.0S 77.0W"**.

This is because letters A through M in UTM coordinates reference the southern hemisphere.
From wikipedia: 

https://en.wikipedia.org/wiki/Universal_Transverse_Mercator_coordinate_system#Latitude_bands_2

> A convenient mnemonic to remember is that the letter "N" is the first letter in "northern hemisphere", so any letter coming before "N" in the alphabet is in the southern hemisphere, and any letter "N" or after is in the northern hemisphere.

**Comment by rolfrander** [comment]
Thank you. Impressed that someone are looking into this old code, the original SO-issue seems to have better solutions available. Sorry that it took so long, but this is fixed and pushed now.

**Comment by rolfrander** [comment]
Fixed and added unit test
